apiVersion: 1

datasources:
  - name: Prometheus - DB Port Monitoring
    uid: grafana-prometheus-datasource
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

